<?php
$this->title = "TabFury Shirt Order Form";
$this->headTitle($this->title);
?>

<!--This will point to the addOrder function in the index controller -->
<p><a class="btn btn-lg btn-success" href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'add'));?>">Order TabFury T-Shirt</a></p>
<table>
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Address</th>
        <th>Shirt Size</th>
        <th>Color</th>
        <th>Shirt Type</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->shirtorderform as $shirtOrder) : ?>
<tr>
    <td><?php echo $this->escape($shirtOrder->firstname);?></td>
    <td><?php echo $this->escape($shirtOrder->lastname);?></td>
    <td><?php echo $this->escape($shirtOrder->address);?></td>
    <td><?php echo $this->escape($shirtOrder->shirtsize);?></td>
    <td><?php echo $this->escape($shirtOrder->color);?></td>
    <td><?php echo $this->escape($shirtOrder->shirttype);?></td>
    <td>
        <!-- this will point to the edit and delete functions of indexcontroller -->
        <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'edit', 'id'=>$shirtOrder->id));?>">Edit</a>
        <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'delete', 'id'=>$shirtOrder->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
        
